module:
  imports:
    path: "github.com/lxndrblz/anatole"
    disable: false
sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: -1
params:
  baseURL: "https://payback159.github.io"
  title: "Alexander Jelinek"
  author: "Alexander Jelinek"
  contentratio: 0.7
  customCss: ["css/syntax.css", "css/skills.css"]
  readMore: true
  description: |-
    Hi there, my name is Alex. ðŸ‘‹ I'm a Platform Engineer & Cloud Architect from Austria.
    Rooted in a strong background of Linux and Open Source, I specialized in orchestrating complex Cloud Native environments.
    I bridge the gap between low-level infrastructure and developer productivity by building resilient, self-healing platforms.
  profilePicture: "images/profile.png"
  socialIcons:
    - icon: "fab fa-github"
      title: "GitHub"
      url: "https://github.com/Payback159"
    - icon: "fab fa-medium"
      title: "Medium"
      url: "https://medium.jelinek.website/"
    - icon: "fab fa-linkedin"
      title: "Linkedin"
      url: "https://www.linkedin.com/in/alexanderjelinek/"
    - icon: "fab fa-xing"
      title: "Xing"
      url: "https://www.xing.com/profile/Alexander_Jelinek4/portfolio"
markup:
  highlight:
    guessSyntax: true
    codeFences: true
    noClasses: true
    style: "github-dark"
    useClasses: true
menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 100
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 200
    - identifier: "portfolio"
      name: "Portfolio"
      url: "/portfolio/"
      weight: 300
related:
  indices:
    - name: "keywords"
      weight: 100
    - name: "tags"
      weight: 80
  includeNewer: true
  threshold: 80
  toLower: true
